"""Object-storage abstraction.

Business logic depends on this protocol only; ``LocalStorage`` (development, single host / shared volume)
and ``S3Storage`` (production; any S3-compatible service) are interchangeable via ``STORAGE_BACKEND``.

The contract is deliberately small and *file-oriented*: geospatial libraries (GDAL) need a real local
path, and uploads can be hundreds of MB, so objects are moved as files/streams, never as ``bytes`` in memory.
Keys are generated by the application (content hash), never derived from user input.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Protocol

_KEY = re.compile(r"^[a-z0-9][a-z0-9/._-]{0,511}$")


class StorageError(Exception):
    """Storage backend failure (treated as transient by the job runner)."""


def validate_key(key: str) -> str:
    if not _KEY.fullmatch(key) or ".." in key or key.startswith("/") or "//" in key:
        raise ValueError(f"invalid storage key: {key!r}")
    return key


class StorageBackend(Protocol):
    name: str

    def put_file(self, key: str, source: Path, content_type: str | None = None) -> None:
        """Store the file at ``source`` under ``key`` (idempotent: same key + same bytes)."""
        ...

    def exists(self, key: str) -> bool: ...

    def download_to(self, key: str, destination: Path) -> Path:
        """Copy the object to ``destination`` (a path the caller owns) and return it."""
        ...

    def delete(self, key: str) -> None: ...

    def check(self) -> None:
        """Raise :class:`StorageError` if the backend is not usable (readiness probe)."""
        ...
