"""Write ``constraints.txt``: exact versions of the dependency closure installed in the current environment.

    python scripts/pin_constraints.py     # run inside the environment the test suite passed in

CI and the Docker image install with ``-c constraints.txt``, so they use the versions that were actually tested
instead of whatever is newest on the day of the build.
"""

from __future__ import annotations

import re
import tomllib
from importlib import metadata
from pathlib import Path

from packaging.requirements import Requirement

ROOT = Path(__file__).resolve().parents[1]
PLATFORM_SPECIFIC = {"colorama", "pywin32", "win32-setctime", "tzdata", "uvloop"}


def normalise(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def closure(requirements: list[str]) -> dict[str, str | None]:
    seen: dict[str, str | None] = {}
    stack = [Requirement(r) for r in requirements]
    while stack:
        requirement = stack.pop()
        name = normalise(requirement.name)
        if name in seen:
            continue
        try:
            distribution = metadata.distribution(requirement.name)
        except metadata.PackageNotFoundError:
            seen[name] = None
            continue
        seen[name] = distribution.version
        for raw in distribution.requires or []:
            dependency = Requirement(raw)
            marker = dependency.marker
            unconditional = marker is None or marker.evaluate({"extra": ""})
            if not unconditional and not any(marker.evaluate({"extra": e}) for e in requirement.extras):  # type: ignore[union-attr]
                continue
            stack.append(dependency)
    return seen


def main() -> None:
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    versions = closure(project["dependencies"]) | closure(project["optional-dependencies"]["dev"])
    lines = [
        "# Exact versions the test suite was run against (generated by scripts/pin_constraints.py).",
        "# Install with: pip install -c constraints.txt -e '.[dev]'",
        "",
    ]
    lines += [f"{n}=={v}" for n, v in sorted(versions.items()) if v is not None and n not in PLATFORM_SPECIFIC]
    if versions.get("psycopg"):
        lines.append(f"psycopg-binary=={versions['psycopg']}")
    (ROOT / "constraints.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"pinned {len(lines) - 3} packages")


if __name__ == "__main__":
    main()
